<a href="https://colab.research.google.com/github/Jangwanko/AI_study/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [ ]:
docs=['너무 재밌네요.', '최고에요.','참 잘 만든 영화에요.','추천하고 싶은 영화입니다.','한번 더 보고싶네요','글쎄요.','별로에요.','생각보다 지루하네요.','연기가 어색해요.','재미없어요.']

In [ ]:
classes=array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
token=Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로에요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [ ]:
x=token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [ ]:
padded_x=pad_sequences(x,4)
"\n패딩결과\n",print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


('\n패딩결과\n', None)

In [ ]:
word_size=len(token.word_index)+1

In [ ]:
model=Sequential()
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(padded_x,classes,epochs=20)


Epoch 1/20
1/1 [==============================] - 1s 896ms/step - loss: 0.6929 - accuracy: 0.6000
Epoch 2/20
1/1 [==============================] - 0s 17ms/step - loss: 0.6905 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6881 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6856 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6832 - accuracy: 0.6000
Epoch 6/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6808 - accuracy: 0.7000
Epoch 7/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6784 - accuracy: 0.7000
Epoch 8/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6759 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6735 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 14ms/step - loss: 0.6710 - accuracy: 0.9000
Epoch 11/20
1/1 [=================

In [ ]:
print("\n Accuracy: %.4f"%(model.evaluate(padded_x,classes)[1]))

1/1 [==============================] - 0s 148ms/step - loss: 0.6440 - accuracy: 0.9000

 Accuracy: 0.9000
